# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install browserstack-cypress-cli
    pwd
  displayName: 'Install BrowserStack Cypress CLI'

- script: |
    cd /home/vsts/work/1/s
    browserstack-cypress run --sync
  displayName: 'Run the Cypress test'
