# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install browserstack-cypress-cli
    pwd
    npx browserstack-cypress run --sync
  displayName: 'Install BrowserStack Cypress CLI & run the test'

# - script: 
#     which browserstack-cypress
#   displayName: 'Check to see where the CLI is installed'

# - script: |
#     browserstack-cypress run --sync
#   displayName: 'Run the Cypress test'
